variable "gcp_project" {}
variable "gcp_region" {}
variable "vpc_network_name" {}
variable "subnet1_name" {}
variable "subnet1_cidr_range" {}
variable "subnet1_region" {}
variable "firewall_rules_name" {}
variable "protocol_to_allow" {}
variable "array_of_ports" {}
variable "subnet2_name" {}
variable "subnet2_cidr_range" {}
variable "subnet2_region" {}
variable "subnet3_name" {}
variable "subnet3_cidr_range" {}
variable "subnet3_region" {}
variable "source_ranges" {}
variable "nginx_webserver_name" {}
variable "nginx_webserver_machine_type" {}
variable "nginx_webserver_image" {}
variable "service_account_id" {}
variable "service_account_name" {}
variable "compute_instance_username" {}
variable "nginx_webserver_disk_name" {}
variable "nginx_webserver_disk_type" {}
variable "nginx_webserver_disk_size" {}
variable "private_key_path" {}
variable "public_key_path" {}