variable "gcp_project" {}
variable "vpc_network_name" {}
variable "subnet1_name" {}
variable "subnet1_cidr_range" {}
variable "subnet1_region" {}
variable "firewall_rules_name" {}
variable "protocol_to_allow" {}
variable "array_of_ports" {}
variable "subnet2_name" {}
variable "subnet2_cidr_range" {}
variable "subnet2_region" {}
variable "subnet3_name" {}
variable "subnet3_cidr_range" {}
variable "subnet3_region" {}