variable "gcp_project" {}
variable "subnet1_id" {}
variable "subnet2_id" {}
variable "subnet3_id" {}
variable "public_ip" {}
variable "subnet1_region" {}
variable "nginx_webserver_name" {}
variable "nginx_webserver_machine_type" {}
variable "nginx_webserver_image" {}
variable "service_account_id" {}
variable "service_account_name" {}
variable "compute_instance_username" {}
variable "nginx_webserver_disk_name" {}
variable "nginx_webserver_disk_type" {}
variable "nginx_webserver_disk_size" {}
variable "private_key_path" {}
variable "public_key_path" {}